AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deployment of FastAPI app to AWS Lambda and API Gateway.

Parameters:
  MySecretName:
    Type: String
    Default: "google_calendar_api_secrets_1"
    Description: The name of the secret in Secrets Manager.

Resources:
  CalendarApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CalendarApiFunction
      Handler: main.handler
      Runtime: python3.10
      CodeUri: ../
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SECRETS_NAME: !Ref MySecretName
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${MySecretName}-*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /calendar/{proxy+}
            Method: ANY

Outputs:
  ApiURL:
    Description: 'URL of the newly created API'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calendar/'
